# Generated by Django 2.0 on 2020-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200716_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.CharField(choices=[('qd', '前端开发'), ('hd', '后端开发'), ('qt', '其他')], max_length=5, verbose_name='课程类别'),
        ),
    ]
