# Generated by Django 2.0 on 2020-07-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bannerinfo_emailverifycode_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfo',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000', verbose_name='图片链接'),
        ),
    ]
